# Generated by Django 3.2.16 on 2023-12-24 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dorm.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='楼栋名称')),
                ('zone', models.CharField(choices=[('first phase', '一期'), ('second phase', '二期'), ('Li Yuan', '荔园'), ('Xin Yuan', '欣园')], max_length=30, verbose_name='地区')),
                ('xlocation', models.FloatField(default=0, verbose_name='经度')),
                ('ylocation', models.FloatField(default=0, verbose_name='纬度')),
                ('buildingDetails', models.TextField(blank=True, max_length=100, null=True, verbose_name='建筑详情')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=dorm.models.Build.photo_upload, verbose_name='图片')),
            ],
            options={
                'verbose_name': '楼栋',
                'verbose_name_plural': '楼栋',
            },
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single_room', '单人间'), ('double_room', '两人间'), ('triple_room', '三人间'), ('quadruple_room', '四人间')], default='quadruple_room', max_length=42, verbose_name='房型')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('roomNumber', models.IntegerField(verbose_name='房间号')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('start', models.DateTimeField(verbose_name='放出时间')),
                ('end', models.DateTimeField(verbose_name='结束时间')),
                ('floorPlan', models.ImageField(blank=True, null=True, upload_to=dorm.models.Dormitory.floor_plan_upload, verbose_name='楼层平面图')),
                ('roomLayout', models.ImageField(blank=True, null=True, upload_to=dorm.models.Dormitory.room_layout_upload, verbose_name='房间布局图')),
                ('degree', models.CharField(choices=[('master', '硕士生'), ('doctor', '博士生')], default='master', max_length=20, verbose_name='学历')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='队伍名称')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_team', to=settings.AUTH_USER_MODEL, verbose_name='队长')),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory', models.OneToOneField(help_text='被选择的宿舍', on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='dorm.dormitory', verbose_name='宿舍')),
                ('team', models.OneToOneField(help_text='成功选上房间的队伍', on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='dorm.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '选择',
                'verbose_name_plural': '选择',
            },
        ),
        migrations.CreateModel(
            name='RoomExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='dorm.dormitory', verbose_name='宿舍')),
                ('fromTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_from', to='dorm.team', verbose_name='出手')),
                ('toTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_to', to='dorm.team', verbose_name='入手')),
            ],
            options={
                'verbose_name': '房间交换',
                'verbose_name_plural': '房间交换',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='文本')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=dorm.models.Message.messagePhoto_upload, verbose_name='图片')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dorm.message', verbose_name='回复')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dorm.team', verbose_name='队伍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
        migrations.CreateModel(
            name='MemberExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user_from', to='dorm.team', verbose_name='出手')),
                ('toTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_user_to', to='dorm.team', verbose_name='入手')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '队员交换',
                'verbose_name_plural': '队员交换',
            },
        ),
        migrations.AddField(
            model_name='dormitory',
            name='bookMarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='dorm.Team', verbose_name='收藏队伍'),
        ),
        migrations.AddField(
            model_name='dormitory',
            name='buildingPosi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dormitories_posi', to='dorm.build', verbose_name='楼栋'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, verbose_name='内容')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='评分')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dorm.dormitory', verbose_name='宿舍')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dorm.comment', verbose_name='回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='房间名')),
                ('photo', models.ImageField(default='users/default.jpeg', upload_to=dorm.models.ChatRoom.roomPhoto_upload, verbose_name='图片')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天室',
                'verbose_name_plural': '聊天室',
            },
        ),
    ]
