# Generated by Django 3.2.16 on 2023-12-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='type',
            field=models.CharField(choices=[('dormitory', '宿舍'), ('facility', '设施')], default='dormitory', max_length=30, verbose_name='类型'),
        ),
    ]
