# Generated by Django 3.2.16 on 2023-12-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_build_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='type',
            field=models.CharField(default='dormitory', max_length=30, verbose_name='类型'),
        ),
    ]
