# Generated by Django 3.2.16 on 2023-12-30 09:21

from django.db import migrations, models
import dorm.models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_alter_build_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitory',
            name='interiorImage',
            field=models.ImageField(blank=True, null=True, upload_to=dorm.models.Dormitory.interiorImage_upload, verbose_name='室内图片'),
        ),
    ]
